### ISSUE TITLE
pass all static requests, but rewrite the api/html requests

### ISSUE THREAD

**Issue by ImHype** [vercel/serve-handler#130]
I have some requests, just like:
```
/page-a
/page-b
/static/xxx/a.aaa.js
/static/xxx/b.bbb.js
```

* `page-a` and `page-b` response `public/index.html`.
* `/static/xxx/a.aaa.js`  response `public/static/xxx/a.aaa.js`
* `/static/xxx/b.bbb.js`  response `public/static/xxx/b.bbb.js`

**Comment by ImHype** [comment]
How could I call the `serve-handler`.

**Comment by rayfoss** [comment]
Negative lookahead is your friend
```
rewrites": [{
    "source": "/((?!api\/.*).*)",
    "destination": "/index.html"
  }]
```

**Comment by ImHype** [comment]
ok. i see
